version: '3.7'

services:

  sample:
    container_name: olio-test 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8001:8000
    environment:
      - CHOKIDAR_USEPOLLING=true

